
export const ModalDialogTypes = {
    // tenant
    TENANT_ITEM_ADD_TYPE: 'TENANT_ITEM_ADD_TYPE',
    TENANT_ITEM_EDIT_TYPE: 'TENANT_ITEM_EDIT_TYPE',    
    TENANT_MEMBER_ADD_TYPE: 'TENANT_MEMBER_ADD_TYPE',

    // user
    USER_ITEM_ADD_TYPE: 'USER_ITEM_ADD_TYPE',
}
